VinMart/Models/Address.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinMart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.AddressUsers = new HashSet<AddressUser>();
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public string province { get; set; }
        public string district { get; set; }
        public string commune { get; set; }
        public string apartmentNumber { get; set; }
    
        public virtual ICollection<AddressUser> AddressUsers { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}

VinMart/Controllers/AcountHomeController.cs
using VinMart.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using VinMart.Models.DTO;
using VinMart.Models.ViewModel;
using VinMart.utils;
using VinMart.Models.DAO;

namespace DoAnWeb3.Controllers
{
    public class AcountHomeController : Controller
    {
         VinMartEntities db = new VinMartEntities();
        
        public ActionResult Home()
        {
           
            return View();
        }

        public ActionResult Acount()
        {

            //Session[UserInfo.UserSession] = data.Accounts.Single(p => p.id == 1);
            //var acount = (Account)Session[UserInfo.UserSession];
            //System.Diagnostics.Debug.WriteLine(acount.id);
            ///var acountDetail = data.AccountDetails.Single(p => p.id == acount.id);
            //AcountFullDetail a = new AcountFullDetail();
            
            UserSession userSession = Session[Constants.Instance.UserSession] as UserSession;
            if (userSession == null)
            {
                return Redirect("/Product/Index");
            }

            var acountDetail = db.AccountDetails.FirstOrDefault(p => p.id == userSession.Id);
            AcountFullDetail a = new AcountFullDetail();
            List<CartDetailProductDTO> cartDetailProducts = new List<CartDetailProductDTO>() { };//has product detail
            cartDetailProducts = CartDAO.Instance.GetAllCardDetailProduct(userSession.Id);

            a.Id = userSession.Id;
            a.DisplayName = userSession.DisplayName;
            a.Email = userSession.Email;
            a.BirthDay = acountDetail.birthDay;
            a.PhoneNumber = acountDetail.phoneNumber;
            a.Gender = acountDetail.gender;
            a.Province = acountDetail.province;
            a.District = acountDetail.district;
            a.Commune = acountDetail.Commune;
            a.Detail = acountDetail.detail;
            a.ApartmentNumber = acountDetail.apartmentNumber;

            AddAccountVM addAccountVM = new AddAccountVM(a, cartDetailProducts);

            return View(addAccountVM);
        }

        [HttpPost, ActionName("Acount")]
        public ActionResult Acount(FormCollection collection)
        {
            //var acount = (Account)Session[UserInfo.UserSession];
            UserSession userSession = Session[Constants.Instance.UserSession] as UserSession;
            if (userSession == null)
            {
                return Redirect("/Product/Index");
            }
            AccountDetail acountDetail = db.AccountDetails.FirstOrDefault(p => p.id == userSession.Id);
            if (acountDetail == null)
            {
                return HttpNotFound();
            }
            userSession.DisplayName = collection["AcountFullDetail.DisplayName"];
            acountDetail.phoneNumber = collection["AcountFullDetail.PhoneNumber"];
            userSession.Email = collection["AcountFullDetail.Email"];
            acountDetail.gender = collection["AcountFullDetail.Gender"];
            //acountDetail.birthDay = DateTime.Parse(String.Format("{mm/dd/yyyy}", collection["AcountFullDetail.BirthDay"]));
            acountDetail.province = collection["AcountFullDetail.Province"];
            acountDetail.district = collection["AcountFullDetail.District"];
            acountDetail.Commune = collection["AcountFullDetail.Commune"];
            acountDetail.apartmentNumber = collection["AcountFullDetail.ApartmentNumber"];

            AcountFullDetail a = new AcountFullDetail();
            a.Id = userSession.Id;
            a.DisplayName = userSession.DisplayName;
            a.Email = userSession.Email;
            a.BirthDay = acountDetail.birthDay;
            a.PhoneNumber = acountDetail.phoneNumber;
            a.Gender = acountDetail.gender;
            a.Province = acountDetail.province;
            a.District = acountDetail.district;
            a.Commune = acountDetail.Commune;
            a.Detail = acountDetail.detail;
            a.ApartmentNumber = acountDetail.apartmentNumber;
            db.SaveChanges();

            List<CartDetailProductDTO> cartDetailProducts = new List<CartDetailProductDTO>() { };//has product detail
            cartDetailProducts = CartDAO.Instance.GetAllCardDetailProduct(userSession.Id);
            AddAccountVM addAccountVM = new AddAccountVM(a, cartDetailProducts);
            return View(addAccountVM);
        }

        [HttpGet]
        public ActionResult Address()
        {
            UserSession userSession = Session[Constants.Instance.UserSession] as UserSession;
            if (userSession == null)
            {
                return Redirect("/Product/Index");
            }
            //List<Address> list = db.Addresses.Where(p => p.id == 1).ToList();
            List<Address> list = db.AddressUsers.Where(a => a.idUser == userSession.Id)
                .Join(db.Addresses,
                a => a.idAddress,
                b => b.id,
                (a, b) => b).ToList();
            List<CartDetailProductDTO> cartDetailProducts = new List<CartDetailProductDTO>() { };//has product detail
            cartDetailProducts = CartDAO.Instance.GetAllCardDetailProduct(userSession.Id);
            AccountListAddressVM accountListAddress = new AccountListAddressVM(cartDetailProducts, list);
            
            return View(accountListAddress);
        }

        [HttpGet]
        public ActionResult AddressAdd()
        {
            UserSession userSession = Session[Constants.Instance.UserSession] as UserSession;
            if (userSession == null)
            {
                return Redirect("/Product/Index");
            }
            List<CartDetailProductDTO> cartDetailProducts = new List<CartDetailProductDTO>() { };//has product detail
            cartDetailProducts = CartDAO.Instance.GetAllCardDetailProduct(userSession.Id);
            Address address = new Address();
            AddAddressVM accountListAddress = new AddAddressVM(cartDetailProducts, address);
            return View(accountListAddress);
        }

        [HttpPost, ActionName("AddressAdd")]
        public ActionResult AddressAdd(FormCollection collection)
        {
            UserSession userSession = Session[Constants.Instance.UserSession] as UserSession;
            if (userSession == null)
            {
                return Redirect("/Product/Index");
            }
            //var acount = (Account)Session[UserInfo.UserSession];
            Address a = new Address();
            a.id = userSession.Id;
            a.name = collection["Address.name"];
            a.phoneNumber = collection["Address.phoneNumber"];
            a.email = collection["Address.email"];
            a.province = collection["Address.province"];
            a.district = collection["Address.district"];
            a.commune = collection["Address.commune"];
            a.apartmentNumber = collection["Address.apartmentNumber"];
            db.Addresses.Add(a);

            AddressUser addressUser = new AddressUser() {
                idAddress = a.id,
                idUser = userSession.Id,
            };
            db.AddressUsers.Add(addressUser);
            db.SaveChanges();
            return RedirectToAction("Address");
        }


        public ActionResult LogOut()
        {
            Session[Constants.Instance.UserSession] = null;
            return Redirect("/Product/Index");
        }

        public ActionResult TransactionHistory()
        {
            //var acount = (Account)Session[UserInfo.UserSession];
            UserSession userSession = Session[Constants.Instance.UserSession] as UserSession;
            if (userSession == null)
            {
                return Redirect("/Product/Index");
            }

            List<Purchase> listPurchase = db.Purchases.Where(p => p.idUser == userSession.Id).OrderByDescending(p => p.createAt).ToList();
            List<PurchaseFullDetail> list = new List<PurchaseFullDetail>();

            List<CartDetailProductDTO> cartDetailProducts = new List<CartDetailProductDTO>() { };//has product detail
            cartDetailProducts = CartDAO.Instance.GetAllCardDetailProduct(userSession.Id);

            foreach (var item in listPurchase)
            {
                List<PurchaseDetail> listDetail = db.PurchaseDetails.Where(p => p.idPurchase == item.id).ToList();
                foreach (var item2 in listDetail)
                {
                    PurchaseFullDetail a = new PurchaseFullDetail();
                    a.Id = item.id;
                    a.IdUser = userSession.Id;
                    a.IdDetail = item2.id;
                    a.CreateAt = item.createAt;
                    a.IdProduct = item2.idProduct;
                    a.Count = item2.count;
                    a.Price = item2.price;
                    a.IdAddress = item.idAddress;
                    Address address = db.Addresses.Where(p => p.id == item.idAddress).FirstOrDefault();

                    a.Province = address.province;
                    a.District = address.district;
                    a.Commune = address.commune;
                    a.ApartmentNumber = address.apartmentNumber;
                    a.DisplayName = db.Products.Where(p => p.id == item2.id).Select(p => p.displayName).FirstOrDefault();

                    list.Add(a);
                }
            }
            HistoryTransactionVM historyTransaction = new HistoryTransactionVM(cartDetailProducts, list);
            return View(historyTransaction);
        }
    }
}

VinMart/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VinMart.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VinMart/Views/AcountHome/Acount.cshtml
@model VinMart.Models.ViewModel.AddAccountVM
@{
    ViewBag.Title = "Acount";
    Layout = "~/Views/AcountHome/Home.cshtml";
}
<head>
    <link href="~/public/css/Acount/Acount.css" />
</head>
@Html.Partial("~/Views/Container/Header.cshtml", Model.CartDetailProducts)
<div style="padding: 32px 64px;">
    <h2 style="margin-top: 0;">Thông tin tài khoản</h2>
    <div>
        @using (Html.BeginForm("Acount", "AcountHome"))
        {
            <fieldset>
                <div class="center-block">
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.DisplayName, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.DisplayName, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                    </div>
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.PhoneNumber, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                    </div>
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.Email, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.Email, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                    </div>
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.Gender, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.Gender, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                        @*<div class="form-group">
                @Html.LabelFor(model => model.AcountFullDetail.BirthDay, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                <div class="col-md-9">
                    @Html.EditorFor(model => model.AcountFullDetail.BirthDay, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                </div>
            </div>*@
                    </div>
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.Province, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.Province, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                    </div>
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.District, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.District, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                    </div>
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.Commune, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.Commune, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                    </div>
                    <div style="min-height: 20px; margin-bottom: 32px">
                        <div class="form-group">
                            @Html.LabelFor(model => model.AcountFullDetail.ApartmentNumber, htmlAttributes: new { @class = "control-label col-md-3 nopadding" })
                            <div class="col-md-9">
                                @Html.EditorFor(model => model.AcountFullDetail.ApartmentNumber, new { htmlAttributes = new { @class = "form-control maxwidth" } })
                            </div>
                        </div>
                    </div>
                    <div>
                        <input type="submit" value="Cập nhật" class="btn btn-success" style="max-width: 100%; width: 100%;" />
                    </div>
                </div>
            </fieldset>
        }
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $('#datetimepicker5').datetimepicker({
            defaultDate: "11/1/2013",
            disabledDates: [
                moment("12/25/2013"),
                new Date(2013, 11 - 1, 21),
                "11/22/2013 00:53"
            ]
        });
    });
</script>
<style>
    .nopadding{
        padding: 0;
    }

    .maxwidth{
        max-width: 100%;
    }
</style>

VinMart/Views/AcountHome/Address.cshtml
@model VinMart.Models.ViewModel.AccountListAddressVM

@{
    ViewBag.Title = "Address";
    Layout = "~/Views/AcountHome/Home.cshtml";
}

<head>
    <link rel="stylesheet" href="~/public/css/Acount/Address.css" />
</head>
@Html.Partial("~/Views/Container/Header.cshtml", Model.CartDetailProducts)

<body>
    <fieldset>
        <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 32px; margin-bottom: 16px;">
            <h2 style="margin: 0;">Address</h2>
            <a class="btn btn-success" href="/AcountHome/AddressAdd">     Thêm    </a>
        </div>
        <div style="min-height: 300px;">
            <table class="table">
                <tr>
                    <th>
                        Họ tên
                    </th>
                    <th>
                        Địa chỉ
                    </th>
                    <th>
                        SDT

                    </th>
                    <th>
                        Email
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.ListAddress)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.name)
                        </td>
                        <td>
                            @item.apartmentNumber, @item.commune, @item.district, @item.province
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.phoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.email)
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "Delete", new { id = item.id })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </fieldset>
</body>

VinMart/Views/AcountHome/AddressAdd.cshtml
@model VinMart.Models.ViewModel.AddAddressVM
@{
    ViewBag.Title = "AddressAdd";
    Layout = "~/Views/AcountHome/Home.cshtml";
}
@Html.Partial("~/Views/Container/Header.cshtml", Model.CartDetailProducts)

<h2>Thêm Địa Chỉ</h2>

@using (Html.BeginForm("AddressAdd", "AcountHome"))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Address.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.phoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address.province, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address.province, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.province, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address.district, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address.district, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.district, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address.commune, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address.commune, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.commune, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address.apartmentNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address.apartmentNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Address.apartmentNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Thêm" class="btn btn-default" />
                </div>
            </div>
        </div>
    </fieldset>
}

VinMart/Views/AcountHome/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <link rel="stylesheet" href="~/public/css/Acount/AcountHome.css" />

    <script src="~/Scripts/jquery-3.4.1.min.js" type="text/javascript"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <link href="~/public/css/base.css" rel="stylesheet" />
    <link href="~/public/fontawesome/css/all.min.css" rel="stylesheet" />
    <link href="~/Scripts/sweetalert.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @*<div class="navbar-left">
            <ul class="main_menu">
                a href="/AcountHome/Acount">Tài Khoản</a>
                <a href="/AcountHome/Address">Sổ Địa Chỉ</a>
                <a href="/AcountHome/TransactionHistory">Lịch Sử Giao Dịch</a>
                <a href="/AcountHome/LogOut">Đăng Xuất</a>
            </ul>
        </div>
        <content class="tab-content">
            @RenderBody()
        </content>*@

    <div class="container" style="margin-top: 120px; margin-bottom: 64px">
        <div class="row">
            <div class="col-lg-4" style="margin-top: 32px;">
                <ul class="list-group">
                    <a class="list-group-item" href="/AcountHome/Acount">Tài Khoản</a>
                    <a class="list-group-item" href="/AcountHome/Address">Sổ Địa Chỉ</a>
                    <a class="list-group-item" href="/AcountHome/TransactionHistory">Lịch Sử Giao Dịch</a>
                    <a class="list-group-item" href="/AcountHome/LogOut">Đăng Xuất</a>
                </ul>
            </div>
            <div class="col-lg-8">
                @RenderBody()
            </div>
        </div>
    </div>
    @RenderPage("../Container/Footer.cshtml")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

<style>
    .list-group-item.active {
        color: #fff;
        background-color: #ff3f39;
    }
</style>

<script>
    console.log($('a[href="@Request.Url.LocalPath"]'))
    $('a[href="@Request.Url.LocalPath"]').addClass('active');
</script>

VinMart/Views/AcountHome/TransactionHistory.cshtml
@model VinMart.Models.ViewModel.HistoryTransactionVM

@{
    ViewBag.Title = "TransactionHistory";
    Layout = "~/Views/AcountHome/Home.cshtml";
}
@*@Html.Partial("~/Views/Container/Header.cshtml", Model.CartDetailProducts)*@
@Html.Partial("~/Views/Container/Header.cshtml", Model.CartDetailProducts)
<h2>Lịch Sử Giao Dịch</h2>
<fieldset>
    <div style="min-height: 300px">
        <table class="table">
            <tr>
                <th>
                    Mã Đơn Hàng
                </th>
                <th>
                    Địa Chỉ
                </th>
                <th>
                    Thời Gian
                </th>
                <th>
                    Sản Phẩm
                </th>
                <th>
                    Số Lượng
                </th>
                <th>
                    Đơn Giá
                </th>
            </tr>

            @foreach (var item in Model.List)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @item.Province, @item.District, @item.Commune, @item.ApartmentNumber
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateAt)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DisplayName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>

        </tr>
            }

        </table>
    </div>
</fieldset>